In [0]:
import numpy as np
import pandas as pd
import keras 
from keras.models import Sequential 
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
 from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/My\ Drive/notebooks\

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/My Drive/notebooks

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df = df_train.append(df_test , ignore_index = True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [0]:
df['Pclass'].isnull().sum(axis=0)
df[['Pclass', 'Survived']].groupby(['Pclass'], as_index=False).mean()
df['Title'] = df.Name.map( lambda x: x.split(',')[1].split( '.' )[0].strip())
df['Title'] = df['Title'].replace('Mlle', 'Miss')
df['Title'] = df['Title'].replace(['Mme','Lady','Ms'], 'Mrs')
df.Title.loc[ (df.Title !=  'Master') & (df.Title !=  'Mr') & (df.Title !=  'Miss') 
             & (df.Title !=  'Mrs')] = 'Others'

# inspect the correlation between Title and Survived
df[['Title', 'Survived']].groupby(['Title'], as_index=False).mean()

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

    Title  Survived
0  Master  0.575000
1    Miss  0.701087
2      Mr  0.156673
3     Mrs  0.796875
4  Others  0.318182

In [0]:
df = pd.concat([df, pd.get_dummies(df['Title'])], axis=1).drop(labels=['Name'], axis=1)
df.Sex = df.Sex.map({'male':0, 'female':1})

In [0]:
df['Family'] = df['SibSp'] + df['Parch'] + 1
df[['Family', 'Survived']].groupby(['Family'], as_index=False).mean()
df.Family = df.Family.map(lambda x: 0 if x > 4 else x)
df[['Family', 'Survived']].groupby(['Family'], as_index=False).mean()

   Family  Survived
0       0  0.161290
1       1  0.303538
2       2  0.552795
3       3  0.578431
4       4  0.724138

In [0]:
df.Ticket = df.Ticket.map(lambda x: x[0])
df[['Ticket', 'Fare']].groupby(['Ticket'], as_index=False).mean()

   Ticket        Fare
0       1   65.771211
1       2   20.235194
2       3   15.380682
3       4   16.764036
4       5   19.262500
5       6   19.153711
6       7    9.197438
7       8    8.397900
8       9    7.750000
9       A   10.189681
10      C   28.152273
11      F   24.677246
12      L    1.515000
13      P  119.698253
14      S   17.542900
15      W   31.056579

In [0]:
df[['Ticket', 'Pclass']].groupby(['Ticket'], as_index=False).mean()

   Ticket    Pclass
0       1  1.147619
1       2  2.309353
2       3  2.904429
3       4  3.000000
4       5  2.333333
5       6  2.111111
6       7  3.000000
7       8  3.000000
8       9  3.000000
9       A  3.000000
10      C  2.558442
11      F  1.846154
12      L  3.000000
13      P  1.102041
14      S  2.561224
15      W  2.315789

In [0]:
df.Ticket[df.Fare.isnull()]
df.Pclass[df.Fare.isnull()]
df.Cabin[df.Fare.isnull()]
df.Embarked[df.Fare.isnull()]
guess_Fare = df.Fare.loc[ (df.Ticket == '3') & (df.Pclass == 3) & (df.Embarked == 'S')].median()
df.Fare.fillna(guess_Fare , inplace=True)

# inspect the mean Fare values for people who died and survived
df[['Fare', 'Survived']].groupby(['Survived'],as_index=False).mean()

   Survived       Fare
0       0.0  22.117887
1       1.0  48.395408

In [0]:
# bin Fare into five intervals with equal amount of people
df['Fare-bin'] = pd.qcut(df.Fare,5,labels=[1,2,3,4,5]).astype(int)

# inspect the correlation between Fare-bin and Survived
df[['Fare-bin', 'Survived']].groupby(['Fare-bin'], as_index=False).mean()

   Fare-bin  Survived
0         1  0.217877
1         2  0.201087
2         3  0.426901
3         4  0.443243
4         5  0.645349

In [0]:
df = df.drop(labels=['Cabin'], axis=1)

In [0]:
df.Embarked.fillna('S' , inplace=True )

In [0]:
df = df.drop(labels='Embarked', axis=1)

In [0]:
df_sub = df[['Age','Master','Miss','Mr','Mrs','Others','Fare-bin','SibSp']]
from sklearn.ensemble import RandomForestRegressor
X_train  = df_sub.dropna().drop('Age', axis=1)
y_train  = df['Age'].dropna()
X_test = df_sub.loc[np.isnan(df.Age)].drop('Age', axis=1)

regressor = RandomForestRegressor(n_estimators = 300)
regressor.fit(X_train, y_train)
y_pred = np.round(regressor.predict(X_test),1)
df.Age.loc[df.Age.isnull()] = y_pred

df.Age.isnull().sum(axis=0)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

0

In [0]:
bins = [ 0, 4, 12, 18, 30, 50, 65, 100] # This is somewhat arbitrary...
age_index = (1,2,3,4,5,6,7)
#('baby','child','teenager','young','mid-age','over-50','senior')
df['Age-bin'] = pd.cut(df.Age, bins, labels=age_index).astype(int)

df[['Age-bin', 'Survived']].groupby(['Age-bin'],as_index=False).mean()

   Age-bin  Survived
0        1  0.675000
1        2  0.452381
2        3  0.402597
3        4  0.315789
4        5  0.427083
5        6  0.375000
6        7  0.125000

In [0]:
df[['Ticket', 'Survived']].groupby(['Ticket'], as_index=False).mean()

   Ticket  Survived
0       1  0.630137
1       2  0.464481
2       3  0.239203
3       4  0.200000
4       5  0.000000
5       6  0.166667
6       7  0.111111
7       8  0.000000
8       9  1.000000
9       A  0.068966
10      C  0.340426
11      F  0.571429
12      L  0.250000
13      P  0.646154
14      S  0.323077
15      W  0.153846

In [0]:
df['Ticket'] = df['Ticket'].replace(['A','W','F','L','5','6','7','8','9'], '4')

# check the correlation again
df[['Ticket', 'Survived']].groupby(['Ticket'], as_index=False).mean()

  Ticket  Survived
0      1  0.630137
1      2  0.464481
2      3  0.239203
3      4  0.166667
4      C  0.340426
5      P  0.646154
6      S  0.323077

In [0]:
df = pd.get_dummies(df,columns=['Ticket'])
df.shape

(1309, 24)

In [0]:
df = df.drop(labels=['SibSp','Parch','Age','Fare','Title'], axis=1)
y_train = df[0:891]['Survived'].values
X_train = df[0:891].drop(['Survived','PassengerId'], axis=1).values
X_test  = df[891:].drop(['Survived','PassengerId'], axis=1).values

In [0]:
from keras.optimizers import Adam
model = Sequential()

# layers
model.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu', input_dim = 17))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
model.compile(optimizer= "adam", loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN
model.fit(X_train, y_train,validation_split=0.1, batch_size = 32, epochs = 200)

Train on 801 samples, validate on 90 samples
Epoch 1/200
801/801 [==============================] - 2s 3ms/step - loss: 0.6804 - acc: 0.6142 - val_loss: 0.6652 - val_acc: 0.6222
Epoch 2/200
801/801 [==============================] - 0s 53us/step - loss: 0.6540 - acc: 0.6142 - val_loss: 0.6319 - val_acc: 0.6222
Epoch 3/200
801/801 [==============================] - 0s 54us/step - loss: 0.6212 - acc: 0.6854 - val_loss: 0.5922 - val_acc: 0.7556
Epoch 4/200
801/801 [==============================] - 0s 59us/step - loss: 0.5791 - acc: 0.7516 - val_loss: 0.5412 - val_acc: 0.8111
Epoch 5/200
801/801 [==============================] - 0s 56us/step - loss: 0.5331 - acc: 0.7903 - val_loss: 0.4911 - val_acc: 0.8444
Epoch 6/200
801/801 [==============================] - 0s 54us/step - loss: 0.4945 - acc: 0.8115 - val_loss: 0.4545 - val_acc: 0.8333
Epoch 7/200
801/801 [==============================] - 0s 57us/step - loss: 0.4660 - acc: 0.8115 - val_loss: 0.4324 - val_acc: 0.8444
Epoch 8/200
801/801 [==============================] - 0s 68us/step - loss: 0.4508 - acc: 0.8177 - val_loss: 0.4243 - val_acc: 0.8333
Epoch 9/200
801/801 [==============================] - 0s 53us/step - loss: 0.4400 - acc: 0.8065 - val_loss: 0.4148 - val_acc: 0.8333
Epoch 10/200
801/801 [==============================] - 0s 55us/step - loss: 0.4370 - acc: 0.8190 - val_loss: 0.4110 - val_acc: 0.8333
Epoch 11/200
801/801 [==============================] - 0s 54us/step - loss: 0.4334 - acc: 0.8065 - val_loss: 0.4072 - val_acc: 0.8333
Epoch 12/200
801/801 [==============================] - 0s 57us/step - loss: 0.4315 - acc: 0.8252 - val_loss: 0.4041 - val_acc: 0.8333
Epoch 13/200
801/801 [==============================] - 0s 57us/step - loss: 0.4283 - acc: 0.8152 - val_loss: 0.3982 - val_acc: 0.8444
Epoch 14/200
801/801 [==============================] - 0s 57us/step - loss: 0.4256 - acc: 0.8165 - val_loss: 0.3975 - val_acc: 0.8444
Epoch 15/200
801/801 [==============================] - 0s 59us/step - loss: 0.4260 - acc: 0.8227 - val_loss: 0.4008 - val_acc: 0.8333
Epoch 16/200
801/801 [==============================] - 0s 60us/step - loss: 0.4239 - acc: 0.8127 - val_loss: 0.3990 - val_acc: 0.8333
Epoch 17/200
801/801 [==============================] - 0s 56us/step - loss: 0.4216 - acc: 0.8165 - val_loss: 0.4014 - val_acc: 0.8333
Epoch 18/200
801/801 [==============================] - 0s 58us/step - loss: 0.4212 - acc: 0.8227 - val_loss: 0.4006 - val_acc: 0.8333
Epoch 19/200
801/801 [==============================] - 0s 54us/step - loss: 0.4197 - acc: 0.8240 - val_loss: 0.3972 - val_acc: 0.8444
Epoch 20/200
801/801 [==============================] - 0s 55us/step - loss: 0.4196 - acc: 0.8227 - val_loss: 0.3971 - val_acc: 0.8333
Epoch 21/200
801/801 [==============================] - 0s 55us/step - loss: 0.4213 - acc: 0.8215 - val_loss: 0.3952 - val_acc: 0.8556
Epoch 22/200
801/801 [==============================] - 0s 55us/step - loss: 0.4190 - acc: 0.8215 - val_loss: 0.3925 - val_acc: 0.8444
Epoch 23/200
801/801 [==============================] - 0s 59us/step - loss: 0.4179 - acc: 0.8252 - val_loss: 0.3941 - val_acc: 0.8556
Epoch 24/200
801/801 [==============================] - 0s 55us/step - loss: 0.4169 - acc: 0.8277 - val_loss: 0.3947 - val_acc: 0.8556
Epoch 25/200
801/801 [==============================] - 0s 56us/step - loss: 0.4174 - acc: 0.8277 - val_loss: 0.3910 - val_acc: 0.8556
Epoch 26/200
801/801 [==============================] - 0s 56us/step - loss: 0.4166 - acc: 0.8327 - val_loss: 0.3928 - val_acc: 0.8556
Epoch 27/200
801/801 [==============================] - 0s 58us/step - loss: 0.4155 - acc: 0.8327 - val_loss: 0.3910 - val_acc: 0.8444
Epoch 28/200
801/801 [==============================] - 0s 54us/step - loss: 0.4148 - acc: 0.8352 - val_loss: 0.3916 - val_acc: 0.8444
Epoch 29/200
801/801 [==============================] - 0s 55us/step - loss: 0.4177 - acc: 0.8202 - val_loss: 0.3932 - val_acc: 0.8444
Epoch 30/200
801/801 [==============================] - 0s 54us/step - loss: 0.4149 - acc: 0.8290 - val_loss: 0.3914 - val_acc: 0.8444
Epoch 31/200
801/801 [==============================] - 0s 62us/step - loss: 0.4138 - acc: 0.8315 - val_loss: 0.3876 - val_acc: 0.8444
Epoch 32/200
801/801 [==============================] - 0s 55us/step - loss: 0.4218 - acc: 0.8202 - val_loss: 0.3870 - val_acc: 0.8444
Epoch 33/200
801/801 [==============================] - 0s 56us/step - loss: 0.4124 - acc: 0.8402 - val_loss: 0.3900 - val_acc: 0.8444
Epoch 34/200
801/801 [==============================] - 0s 54us/step - loss: 0.4129 - acc: 0.8340 - val_loss: 0.3900 - val_acc: 0.8444
Epoch 35/200
801/801 [==============================] - 0s 66us/step - loss: 0.4158 - acc: 0.8265 - val_loss: 0.3913 - val_acc: 0.8556
Epoch 36/200
801/801 [==============================] - 0s 54us/step - loss: 0.4171 - acc: 0.8240 - val_loss: 0.3837 - val_acc: 0.8444
Epoch 37/200
801/801 [==============================] - 0s 57us/step - loss: 0.4116 - acc: 0.8327 - val_loss: 0.3864 - val_acc: 0.8556
Epoch 38/200
801/801 [==============================] - 0s 67us/step - loss: 0.4150 - acc: 0.8252 - val_loss: 0.3854 - val_acc: 0.8444
Epoch 39/200
801/801 [==============================] - 0s 55us/step - loss: 0.4137 - acc: 0.8340 - val_loss: 0.3893 - val_acc: 0.8444
Epoch 40/200
801/801 [==============================] - 0s 55us/step - loss: 0.4127 - acc: 0.8277 - val_loss: 0.3880 - val_acc: 0.8444
Epoch 41/200
801/801 [==============================] - 0s 56us/step - loss: 0.4117 - acc: 0.8315 - val_loss: 0.3870 - val_acc: 0.8444
Epoch 42/200
801/801 [==============================] - 0s 57us/step - loss: 0.4117 - acc: 0.8340 - val_loss: 0.3875 - val_acc: 0.8444
Epoch 43/200
801/801 [==============================] - 0s 59us/step - loss: 0.4109 - acc: 0.8352 - val_loss: 0.3901 - val_acc: 0.8444
Epoch 44/200
801/801 [==============================] - 0s 54us/step - loss: 0.4108 - acc: 0.8315 - val_loss: 0.3875 - val_acc: 0.8444
Epoch 45/200
801/801 [==============================] - 0s 59us/step - loss: 0.4108 - acc: 0.8340 - val_loss: 0.3892 - val_acc: 0.8556
Epoch 46/200
801/801 [==============================] - 0s 58us/step - loss: 0.4098 - acc: 0.8352 - val_loss: 0.3892 - val_acc: 0.8556
Epoch 47/200
801/801 [==============================] - 0s 55us/step - loss: 0.4102 - acc: 0.8327 - val_loss: 0.3895 - val_acc: 0.8444
Epoch 48/200
801/801 [==============================] - 0s 57us/step - loss: 0.4172 - acc: 0.8277 - val_loss: 0.3893 - val_acc: 0.8444
Epoch 49/200
801/801 [==============================] - 0s 57us/step - loss: 0.4161 - acc: 0.8215 - val_loss: 0.3796 - val_acc: 0.8444
Epoch 50/200
801/801 [==============================] - 0s 58us/step - loss: 0.4114 - acc: 0.8190 - val_loss: 0.3838 - val_acc: 0.8333
Epoch 51/200
801/801 [==============================] - 0s 58us/step - loss: 0.4094 - acc: 0.8340 - val_loss: 0.3849 - val_acc: 0.8444
Epoch 52/200
801/801 [==============================] - 0s 58us/step - loss: 0.4090 - acc: 0.8315 - val_loss: 0.3835 - val_acc: 0.8444
Epoch 53/200
801/801 [==============================] - 0s 55us/step - loss: 0.4109 - acc: 0.8327 - val_loss: 0.3825 - val_acc: 0.8444
Epoch 54/200
801/801 [==============================] - 0s 55us/step - loss: 0.4107 - acc: 0.8315 - val_loss: 0.3842 - val_acc: 0.8444
Epoch 55/200
801/801 [==============================] - 0s 55us/step - loss: 0.4094 - acc: 0.8340 - val_loss: 0.3832 - val_acc: 0.8556
Epoch 56/200
801/801 [==============================] - 0s 57us/step - loss: 0.4097 - acc: 0.8277 - val_loss: 0.3806 - val_acc: 0.8444
Epoch 57/200
801/801 [==============================] - 0s 54us/step - loss: 0.4086 - acc: 0.8315 - val_loss: 0.3815 - val_acc: 0.8556
Epoch 58/200
801/801 [==============================] - 0s 55us/step - loss: 0.4083 - acc: 0.8365 - val_loss: 0.3839 - val_acc: 0.8444
Epoch 59/200
801/801 [==============================] - 0s 54us/step - loss: 0.4115 - acc: 0.8277 - val_loss: 0.3827 - val_acc: 0.8444
Epoch 60/200
801/801 [==============================] - 0s 57us/step - loss: 0.4082 - acc: 0.8340 - val_loss: 0.3789 - val_acc: 0.8556
Epoch 61/200
801/801 [==============================] - 0s 59us/step - loss: 0.4091 - acc: 0.8315 - val_loss: 0.3808 - val_acc: 0.8556
Epoch 62/200
801/801 [==============================] - 0s 53us/step - loss: 0.4080 - acc: 0.8365 - val_loss: 0.3797 - val_acc: 0.8556
Epoch 63/200
801/801 [==============================] - 0s 54us/step - loss: 0.4068 - acc: 0.8365 - val_loss: 0.3813 - val_acc: 0.8556
Epoch 64/200
801/801 [==============================] - 0s 55us/step - loss: 0.4075 - acc: 0.8390 - val_loss: 0.3797 - val_acc: 0.8556
Epoch 65/200
801/801 [==============================] - 0s 53us/step - loss: 0.4071 - acc: 0.8352 - val_loss: 0.3814 - val_acc: 0.8556
Epoch 66/200
801/801 [==============================] - 0s 54us/step - loss: 0.4128 - acc: 0.8302 - val_loss: 0.3858 - val_acc: 0.8444
Epoch 67/200
801/801 [==============================] - 0s 55us/step - loss: 0.4074 - acc: 0.8365 - val_loss: 0.3822 - val_acc: 0.8556
Epoch 68/200
801/801 [==============================] - 0s 57us/step - loss: 0.4066 - acc: 0.8365 - val_loss: 0.3823 - val_acc: 0.8556
Epoch 69/200
801/801 [==============================] - 0s 57us/step - loss: 0.4078 - acc: 0.8365 - val_loss: 0.3885 - val_acc: 0.8556
Epoch 70/200
801/801 [==============================] - 0s 56us/step - loss: 0.4078 - acc: 0.8365 - val_loss: 0.3812 - val_acc: 0.8556
Epoch 71/200
801/801 [==============================] - 0s 53us/step - loss: 0.4062 - acc: 0.8390 - val_loss: 0.3824 - val_acc: 0.8556
Epoch 72/200
801/801 [==============================] - 0s 56us/step - loss: 0.4059 - acc: 0.8365 - val_loss: 0.3816 - val_acc: 0.8556
Epoch 73/200
801/801 [==============================] - 0s 54us/step - loss: 0.4059 - acc: 0.8377 - val_loss: 0.3804 - val_acc: 0.8556
Epoch 74/200
801/801 [==============================] - 0s 53us/step - loss: 0.4067 - acc: 0.8365 - val_loss: 0.3803 - val_acc: 0.8556
Epoch 75/200
801/801 [==============================] - 0s 55us/step - loss: 0.4071 - acc: 0.8352 - val_loss: 0.3851 - val_acc: 0.8556
Epoch 76/200
801/801 [==============================] - 0s 62us/step - loss: 0.4093 - acc: 0.8340 - val_loss: 0.3817 - val_acc: 0.8556
Epoch 77/200
801/801 [==============================] - 0s 56us/step - loss: 0.4065 - acc: 0.8327 - val_loss: 0.3787 - val_acc: 0.8556
Epoch 78/200
801/801 [==============================] - 0s 54us/step - loss: 0.4078 - acc: 0.8327 - val_loss: 0.3828 - val_acc: 0.8556
Epoch 79/200
801/801 [==============================] - 0s 56us/step - loss: 0.4068 - acc: 0.8352 - val_loss: 0.3800 - val_acc: 0.8556
Epoch 80/200
801/801 [==============================] - 0s 64us/step - loss: 0.4066 - acc: 0.8377 - val_loss: 0.3803 - val_acc: 0.8556
Epoch 81/200
801/801 [==============================] - 0s 57us/step - loss: 0.4082 - acc: 0.8340 - val_loss: 0.3802 - val_acc: 0.8667
Epoch 82/200
801/801 [==============================] - 0s 53us/step - loss: 0.4060 - acc: 0.8352 - val_loss: 0.3812 - val_acc: 0.8556
Epoch 83/200
801/801 [==============================] - 0s 57us/step - loss: 0.4057 - acc: 0.8390 - val_loss: 0.3827 - val_acc: 0.8556
Epoch 84/200
801/801 [==============================] - 0s 56us/step - loss: 0.4051 - acc: 0.8377 - val_loss: 0.3804 - val_acc: 0.8556
Epoch 85/200
801/801 [==============================] - 0s 54us/step - loss: 0.4058 - acc: 0.8352 - val_loss: 0.3798 - val_acc: 0.8667
Epoch 86/200
801/801 [==============================] - 0s 54us/step - loss: 0.4095 - acc: 0.8340 - val_loss: 0.3818 - val_acc: 0.8556
Epoch 87/200
801/801 [==============================] - 0s 53us/step - loss: 0.4084 - acc: 0.8365 - val_loss: 0.3834 - val_acc: 0.8667
Epoch 88/200
801/801 [==============================] - 0s 52us/step - loss: 0.4053 - acc: 0.8377 - val_loss: 0.3812 - val_acc: 0.8667
Epoch 89/200
801/801 [==============================] - 0s 52us/step - loss: 0.4053 - acc: 0.8365 - val_loss: 0.3824 - val_acc: 0.8667
Epoch 90/200
801/801 [==============================] - 0s 53us/step - loss: 0.4087 - acc: 0.8327 - val_loss: 0.3865 - val_acc: 0.8556
Epoch 91/200
801/801 [==============================] - 0s 55us/step - loss: 0.4058 - acc: 0.8377 - val_loss: 0.3798 - val_acc: 0.8556
Epoch 92/200
801/801 [==============================] - 0s 54us/step - loss: 0.4067 - acc: 0.8315 - val_loss: 0.3779 - val_acc: 0.8556
Epoch 93/200
801/801 [==============================] - 0s 55us/step - loss: 0.4048 - acc: 0.8365 - val_loss: 0.3791 - val_acc: 0.8556
Epoch 94/200
801/801 [==============================] - 0s 54us/step - loss: 0.4056 - acc: 0.8365 - val_loss: 0.3814 - val_acc: 0.8556
Epoch 95/200
801/801 [==============================] - 0s 54us/step - loss: 0.4044 - acc: 0.8365 - val_loss: 0.3786 - val_acc: 0.8556
Epoch 96/200
801/801 [==============================] - 0s 55us/step - loss: 0.4059 - acc: 0.8340 - val_loss: 0.3813 - val_acc: 0.8556
Epoch 97/200
801/801 [==============================] - 0s 58us/step - loss: 0.4042 - acc: 0.8377 - val_loss: 0.3778 - val_acc: 0.8556
Epoch 98/200
801/801 [==============================] - 0s 57us/step - loss: 0.4061 - acc: 0.8252 - val_loss: 0.3743 - val_acc: 0.8556
Epoch 99/200
801/801 [==============================] - 0s 57us/step - loss: 0.4040 - acc: 0.8365 - val_loss: 0.3782 - val_acc: 0.8444
Epoch 100/200
801/801 [==============================] - 0s 56us/step - loss: 0.4040 - acc: 0.8365 - val_loss: 0.3794 - val_acc: 0.8444
Epoch 101/200
801/801 [==============================] - 0s 54us/step - loss: 0.4051 - acc: 0.8302 - val_loss: 0.3782 - val_acc: 0.8556
Epoch 102/200
801/801 [==============================] - 0s 56us/step - loss: 0.4040 - acc: 0.8365 - val_loss: 0.3785 - val_acc: 0.8556
Epoch 103/200
801/801 [==============================] - 0s 54us/step - loss: 0.4044 - acc: 0.8352 - val_loss: 0.3793 - val_acc: 0.8444
Epoch 104/200
801/801 [==============================] - 0s 54us/step - loss: 0.4037 - acc: 0.8352 - val_loss: 0.3772 - val_acc: 0.8444
Epoch 105/200
801/801 [==============================] - 0s 54us/step - loss: 0.4055 - acc: 0.8290 - val_loss: 0.3813 - val_acc: 0.8333
Epoch 106/200
801/801 [==============================] - 0s 54us/step - loss: 0.4036 - acc: 0.8340 - val_loss: 0.3797 - val_acc: 0.8444
Epoch 107/200
801/801 [==============================] - 0s 56us/step - loss: 0.4032 - acc: 0.8340 - val_loss: 0.3787 - val_acc: 0.8444
Epoch 108/200
801/801 [==============================] - 0s 56us/step - loss: 0.4040 - acc: 0.8327 - val_loss: 0.3805 - val_acc: 0.8333
Epoch 109/200
801/801 [==============================] - 0s 54us/step - loss: 0.4044 - acc: 0.8352 - val_loss: 0.3804 - val_acc: 0.8333
Epoch 110/200
801/801 [==============================] - 0s 59us/step - loss: 0.4034 - acc: 0.8340 - val_loss: 0.3784 - val_acc: 0.8444
Epoch 111/200
801/801 [==============================] - 0s 56us/step - loss: 0.4030 - acc: 0.8327 - val_loss: 0.3766 - val_acc: 0.8333
Epoch 112/200
801/801 [==============================] - 0s 56us/step - loss: 0.4023 - acc: 0.8290 - val_loss: 0.3799 - val_acc: 0.8333
Epoch 113/200
801/801 [==============================] - 0s 54us/step - loss: 0.4037 - acc: 0.8327 - val_loss: 0.3767 - val_acc: 0.8444
Epoch 114/200
801/801 [==============================] - 0s 55us/step - loss: 0.4022 - acc: 0.8327 - val_loss: 0.3796 - val_acc: 0.8333
Epoch 115/200
801/801 [==============================] - 0s 52us/step - loss: 0.4045 - acc: 0.8315 - val_loss: 0.3785 - val_acc: 0.8333
Epoch 116/200
801/801 [==============================] - 0s 54us/step - loss: 0.4032 - acc: 0.8327 - val_loss: 0.3749 - val_acc: 0.8333
Epoch 117/200
801/801 [==============================] - 0s 52us/step - loss: 0.4017 - acc: 0.8340 - val_loss: 0.3734 - val_acc: 0.8444
Epoch 118/200
801/801 [==============================] - 0s 56us/step - loss: 0.4020 - acc: 0.8340 - val_loss: 0.3728 - val_acc: 0.8444
Epoch 119/200
801/801 [==============================] - 0s 55us/step - loss: 0.4031 - acc: 0.8352 - val_loss: 0.3752 - val_acc: 0.8556
Epoch 120/200
801/801 [==============================] - 0s 56us/step - loss: 0.4044 - acc: 0.8327 - val_loss: 0.3796 - val_acc: 0.8444
Epoch 121/200
801/801 [==============================] - 0s 67us/step - loss: 0.4068 - acc: 0.8352 - val_loss: 0.3742 - val_acc: 0.8333
Epoch 122/200
801/801 [==============================] - 0s 56us/step - loss: 0.4011 - acc: 0.8340 - val_loss: 0.3712 - val_acc: 0.8333
Epoch 123/200
801/801 [==============================] - 0s 55us/step - loss: 0.4013 - acc: 0.8377 - val_loss: 0.3718 - val_acc: 0.8333
Epoch 124/200
801/801 [==============================] - 0s 64us/step - loss: 0.4012 - acc: 0.8365 - val_loss: 0.3708 - val_acc: 0.8444
Epoch 125/200
801/801 [==============================] - 0s 58us/step - loss: 0.4009 - acc: 0.8377 - val_loss: 0.3702 - val_acc: 0.8556
Epoch 126/200
801/801 [==============================] - 0s 56us/step - loss: 0.4011 - acc: 0.8377 - val_loss: 0.3724 - val_acc: 0.8333
Epoch 127/200
801/801 [==============================] - 0s 54us/step - loss: 0.4079 - acc: 0.8227 - val_loss: 0.3712 - val_acc: 0.8333
Epoch 128/200
801/801 [==============================] - 0s 53us/step - loss: 0.4032 - acc: 0.8365 - val_loss: 0.3680 - val_acc: 0.8444
Epoch 129/200
801/801 [==============================] - 0s 52us/step - loss: 0.4074 - acc: 0.8277 - val_loss: 0.3749 - val_acc: 0.8333
Epoch 130/200
801/801 [==============================] - 0s 54us/step - loss: 0.4055 - acc: 0.8227 - val_loss: 0.3672 - val_acc: 0.8444
Epoch 131/200
801/801 [==============================] - 0s 53us/step - loss: 0.4029 - acc: 0.8302 - val_loss: 0.3692 - val_acc: 0.8444
Epoch 132/200
801/801 [==============================] - 0s 55us/step - loss: 0.4034 - acc: 0.8302 - val_loss: 0.3748 - val_acc: 0.8333
Epoch 133/200
801/801 [==============================] - 0s 53us/step - loss: 0.4008 - acc: 0.8327 - val_loss: 0.3721 - val_acc: 0.8444
Epoch 134/200
801/801 [==============================] - 0s 54us/step - loss: 0.4018 - acc: 0.8340 - val_loss: 0.3778 - val_acc: 0.8333
Epoch 135/200
801/801 [==============================] - 0s 59us/step - loss: 0.4017 - acc: 0.8352 - val_loss: 0.3749 - val_acc: 0.8444
Epoch 136/200
801/801 [==============================] - 0s 53us/step - loss: 0.4000 - acc: 0.8352 - val_loss: 0.3742 - val_acc: 0.8444
Epoch 137/200
801/801 [==============================] - 0s 55us/step - loss: 0.4001 - acc: 0.8327 - val_loss: 0.3733 - val_acc: 0.8444
Epoch 138/200
801/801 [==============================] - 0s 54us/step - loss: 0.4014 - acc: 0.8365 - val_loss: 0.3755 - val_acc: 0.8333
Epoch 139/200
801/801 [==============================] - 0s 55us/step - loss: 0.4072 - acc: 0.8340 - val_loss: 0.3773 - val_acc: 0.8333
Epoch 140/200
801/801 [==============================] - 0s 60us/step - loss: 0.4046 - acc: 0.8377 - val_loss: 0.3705 - val_acc: 0.8556
Epoch 141/200
801/801 [==============================] - 0s 55us/step - loss: 0.4001 - acc: 0.8390 - val_loss: 0.3689 - val_acc: 0.8556
Epoch 142/200
801/801 [==============================] - 0s 54us/step - loss: 0.4025 - acc: 0.8365 - val_loss: 0.3685 - val_acc: 0.8556
Epoch 143/200
801/801 [==============================] - 0s 54us/step - loss: 0.3989 - acc: 0.8352 - val_loss: 0.3722 - val_acc: 0.8333
Epoch 144/200
801/801 [==============================] - 0s 54us/step - loss: 0.4009 - acc: 0.8365 - val_loss: 0.3689 - val_acc: 0.8333
Epoch 145/200
801/801 [==============================] - 0s 53us/step - loss: 0.3990 - acc: 0.8352 - val_loss: 0.3667 - val_acc: 0.8333
Epoch 146/200
801/801 [==============================] - 0s 54us/step - loss: 0.3988 - acc: 0.8352 - val_loss: 0.3672 - val_acc: 0.8333
Epoch 147/200
801/801 [==============================] - 0s 62us/step - loss: 0.4001 - acc: 0.8352 - val_loss: 0.3624 - val_acc: 0.8444
Epoch 148/200

In [0]:
y_pred = model.predict(X_test)
y_final = (y_pred > 0.5).astype(int).reshape(X_test.shape[0])

output = pd.DataFrame({'PassengerId': df_test['PassengerId'], 'Survived': y_final})
output.to_csv('prediction-ann9.csv', index=False)